<a href="https://colab.research.google.com/github/victordsrocha/Metodos-Numericos-2/blob/main/Tarefa11_victorrocha433475.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve


def potencia_inverso(A, v0, erro):
    lu, piv = lu_factor(A)
    lambda_inv_novo = 0
    v_novo = v0

    lambda_inv_velho = lambda_inv_novo
    v_velho = v_novo
    x_velho = v_velho / np.linalg.norm(v_velho)
    v_novo = lu_solve((lu, piv), x_velho)
    lambda_inv_novo = x_velho.T @ v_novo

    while (abs(lambda_inv_novo - lambda_inv_velho)) / lambda_inv_novo > erro:
        lambda_inv_velho = lambda_inv_novo
        v_velho = v_novo
        x_velho = v_velho / np.linalg.norm(v_velho)
        v_novo = lu_solve((lu, piv), x_velho)
        lambda_inv_novo = x_velho.T @ v_novo

    lambda_n = 1 / lambda_inv_novo
    x_n = x_velho
    return lambda_n, x_n


def potencia_deslocamento(A, v0, erro, u):
    I = np.copy(A)
    for i in range(len(A)):
        for j in range(len(A)):
            if i == j:
                I[i][j] = 1
            else:
                I[i][j] = 0

    A_ = A - (I * u)
    lambda_, x_ = potencia_inverso(A_, v0, erro)
    lambda_ = lambda_ + u
    return lambda_, x_

# imprime os resultados utilizando os dois métodos
def Resultado(A, v0, erro):
    print("Matriz: \n{}".format(A))
    erro = 0.00001
    print("\nMétodo: Potência Inverso 2.1b; Erro: {}".format(erro))
    print("Resultados:")
    lambda_n, x_n = potencia_inverso(A, v0, erro)
    print("Lambda_n = {}; x_n = {}".format(lambda_n, x_n))
    print("\n")
    print("\nMétodo: Potência com deslocamento; Erro: {}".format(erro))
    print("Resultados:")
    lambda_n, x_n = potencia_inverso(A, v0, erro)
    print("Lambda_n = {}; x_n = {}".format(lambda_n, x_n))
    print("~~~~~~~~~~~~~~~~~~~~~~\n\n")


# gera os resultados para cada matriz dada no problema
print("Matriz 1:")
A1 = np.array([[5., 2., 1.], [2., 3., 1.], [1., 1., 2.]])
v0 = np.array([1., 1., 1.])
Resultado(A1, v0, 0.00001)

print("Matriz 2:")
A2 = np.array([[-14., 1., -2.], [1., -1., 1.], [-2., 1., -11.]])
v0 = np.array([1., 1., 1.])
Resultado(A2, v0, 0.00001)

print("Matriz 3:")
A3 = np.array([[40., 8., 4., 2., 1.], [8., 30., 12., 6., 2.], [4., 12., 20., 1., 2.], [2., 6., 1., 25., 4.],
              [1., 2., 2., 4., 5.]])
v0 = np.array([1., 1., 1., 1., 1.])
Resultado(A3, v0, 0.00001)


Matriz 1:
Matriz: 
[[5. 2. 1.]
 [2. 3. 1.]
 [1. 1. 2.]]

Método: Potência Inverso 2.1b; Erro: 1e-05
Resultados:
Lambda_n = 1.3542562571753827; x_n = [ 0.13310677 -0.62713798  0.76745068]



Método: Potência com deslocamento; Erro: 1e-05
Resultados:
Lambda_n = 1.3542562571753827; x_n = [ 0.13310677 -0.62713798  0.76745068]
~~~~~~~~~~~~~~~~~~~~~~


Matriz 2:
Matriz: 
[[-14.   1.  -2.]
 [  1.  -1.   1.]
 [ -2.   1. -11.]]

Método: Potência Inverso 2.1b; Erro: 1e-05
Resultados:
Lambda_n = -1.816901408450704; x_n = [0.57735027 0.57735027 0.57735027]



Método: Potência com deslocamento; Erro: 1e-05
Resultados:
Lambda_n = -1.816901408450704; x_n = [0.57735027 0.57735027 0.57735027]
~~~~~~~~~~~~~~~~~~~~~~


Matriz 3:
Matriz: 
[[40.  8.  4.  2.  1.]
 [ 8. 30. 12.  6.  2.]
 [ 4. 12. 20.  1.  2.]
 [ 2.  6.  1. 25.  4.]
 [ 1.  2.  2.  4.  5.]]

Método: Potência Inverso 2.1b; Erro: 1e-05
Resultados:
Lambda_n = 4.014887578587438; x_n = [-0.00904129  0.03127975 -0.1307626  -0.18723053  0.97302914]

