<a href="https://colab.research.google.com/github/victordsrocha/Metodos-Numericos-2/blob/main/Tarefa11_VictorRocha433475.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


def potencia_regular(A, v0, erro):
    lambda_novo = 0
    v_novo = v0

    # primeira iteração antes de entrar no while
    lambda_velho = lambda_novo
    v_velho = v_novo
    x_velho = v_velho / np.linalg.norm(v_velho)  # linalg.norm retorna a norma do vetor
    v_novo = A @ x_velho  # O operador @ retorna o produto matricial
    lambda_novo = x_velho @ v_novo

    while (abs(lambda_novo - lambda_velho)) / lambda_novo > erro:
        lambda_velho = lambda_novo
        v_velho = v_novo
        x_velho = v_velho / np.linalg.norm(v_velho)
        v_novo = A @ x_velho
        lambda_novo = x_velho @ v_novo

    return lambda_novo, x_velho


def Resultado(A, v0, erro):
    print("\nMatriz A: \n{}".format(A))
    erro = 0.00001
    print("\nMétodo: Potência regular; Erro: {}".format(erro))
    print("Resultados:")
    lambda_n, x_n = potencia_regular(A, v0, erro)
    print("Lambda = {}; x = {}".format(lambda_n, x_n))
    print('\n~~~~~~~~')


A = np.array([[5., 2., 1.], [2., 3., 1.], [1., 1., 2.]])
v0 = np.array([1., 1., 1.])
Resultado(A, v0, 0.00001)

A = np.array([[40., 8., 4., 2., 1.], [8., 30., 12., 6., 2.], [4., 12., 20., 1., 2.], [2., 6., 1., 25., 4.],
              [1., 2., 2., 4., 5.]])
v0 = np.array([1., 1., 1., 1., 1.])
Resultado(A, v0, 0.00001)



Matriz A: 
[[5. 2. 1.]
 [2. 3. 1.]
 [1. 1. 2.]]

Método: Potência regular; Erro: 1e-05
Resultados:
Lambda = 6.645747653786828; x = [0.80466984 0.52041512 0.28578761]

~~~~~~~~

Matriz A: 
[[40.  8.  4.  2.  1.]
 [ 8. 30. 12.  6.  2.]
 [ 4. 12. 20.  1.  2.]
 [ 2.  6.  1. 25.  4.]
 [ 1.  2.  2.  4.  5.]]

Método: Potência regular; Erro: 1e-05
Resultados:
Lambda = 49.38296638270153; x = [0.69584742 0.58140935 0.34584366 0.22813204 0.07815033]

~~~~~~~~
